In [91]:
# Import libraries

from pathlib import Path

import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 160)
pd.set_option("display.max_colwidth", 120)

In [92]:
# Define project paths

PROJECT_ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()

RAW_DIR = PROJECT_ROOT / "data" / "01_raw" / "cms_exchange_pufs"
PREPROCESSED_DIR = PROJECT_ROOT / "data" / "02_preprocessed"

PREPROCESSED_DIR.mkdir(parents=True, exist_ok=True)

print("PROJECT_ROOT:", PROJECT_ROOT)
print("RAW_DIR:", RAW_DIR)
print("PREPROCESSED_DIR:", PREPROCESSED_DIR)

PROJECT_ROOT: c:\Users\tevin\OneDrive\Desktop\LLM-And-Generative-AI\rag\benefits_ai_platform
RAW_DIR: c:\Users\tevin\OneDrive\Desktop\LLM-And-Generative-AI\rag\benefits_ai_platform\data\01_raw\cms_exchange_pufs
PREPROCESSED_DIR: c:\Users\tevin\OneDrive\Desktop\LLM-And-Generative-AI\rag\benefits_ai_platform\data\02_preprocessed

In [93]:
# Find all CSV files in the CMS Exchange PUF raw folder

csv_files = sorted(RAW_DIR.rglob("*.csv"))

print("CSV files found:", len(csv_files))

for i, file_path in enumerate(csv_files):
    print(i, file_path.relative_to(PROJECT_ROOT))

CSV files found: 3
0 data\01_raw\cms_exchange_pufs\Benefits_Cost_Sharing_PUF.csv
1 data\01_raw\cms_exchange_pufs\Plan_Attributes_PUF.csv
2 data\01_raw\cms_exchange_pufs\Rate_PUF.csv

In [94]:
# Auto-detect the main CMS PUF files

def find_file_by_keywords(files, keywords):
    matches = []

    for file_path in files:
        file_path_text = str(file_path).lower()

        if all(keyword.lower() in file_path_text for keyword in keywords):
            matches.append(file_path)

    return matches


plan_matches = find_file_by_keywords(csv_files, ["plan"])
benefit_matches = find_file_by_keywords(csv_files, ["benefit"])
rate_matches = find_file_by_keywords(csv_files, ["rate"])

print("Plan matches:")
for i, file_path in enumerate(plan_matches):
    print(i, file_path.relative_to(PROJECT_ROOT))

print("\nBenefit matches:")
for i, file_path in enumerate(benefit_matches):
    print(i, file_path.relative_to(PROJECT_ROOT))

print("\nRate matches:")
for i, file_path in enumerate(rate_matches):
    print(i, file_path.relative_to(PROJECT_ROOT))

Plan matches:
0 data\01_raw\cms_exchange_pufs\Plan_Attributes_PUF.csv

Benefit matches:
0 data\01_raw\cms_exchange_pufs\Benefits_Cost_Sharing_PUF.csv
1 data\01_raw\cms_exchange_pufs\Plan_Attributes_PUF.csv
2 data\01_raw\cms_exchange_pufs\Rate_PUF.csv

Rate matches:
0 data\01_raw\cms_exchange_pufs\Rate_PUF.csv

In [95]:
# Select the main plan, benefits, and rate files

plan_file = plan_matches[0]
benefits_file = benefit_matches[0]
rate_file = rate_matches[0]

print("Plan file:", plan_file.relative_to(PROJECT_ROOT))
print("Benefits file:", benefits_file.relative_to(PROJECT_ROOT))
print("Rate file:", rate_file.relative_to(PROJECT_ROOT))

Plan file: data\01_raw\cms_exchange_pufs\Plan_Attributes_PUF.csv
Benefits file: data\01_raw\cms_exchange_pufs\Benefits_Cost_Sharing_PUF.csv
Rate file: data\01_raw\cms_exchange_pufs\Rate_PUF.csv

In [96]:
# Load the Plan Attributes file
# This is the main file for plan-level metadata.

plan_df = pd.read_csv(plan_file, low_memory=False)

print("Plan data shape:", plan_df.shape)
display(plan_df.head())

Plan data shape: (22059, 151)

,BusinessYear,StateCode,IssuerId,IssuerMarketPlaceMarketingName,SourceName,ImportDate,MarketCoverage,DentalOnlyPlan,StandardComponentId,PlanMarketingName,HIOSProductId,NetworkId,ServiceAreaId,FormularyId,IsNewPlan,PlanType,MetalLevel,DesignType,UniquePlanDesign,QHPNonQHPTypeId,IsNoticeRequiredForPregnancy,IsReferralRequiredForSpecialist,SpecialistRequiringReferral,PlanLevelExclusions,IndianPlanVariationEstimatedAdvancedPaymentAmountPerEnrollee,CompositeRatingOffered,ChildOnlyOffering,ChildOnlyPlanId,WellnessProgramOffered,DiseaseManagementProgramsOffered,EHBPercentTotalPremium,EHBPediatricDentalApportionmentQuantity,IsGuaranteedRate,PlanEffectiveDate,PlanExpirationDate,OutOfCountryCoverage,OutOfCountryCoverageDescription,OutOfServiceAreaCoverage,OutOfServiceAreaCoverageDescription,NationalNetwork,URLForEnrollmentPayment,FormularyURL,PlanId,PlanVariantMarketingName,CSRVariationType,IssuerActuarialValue,AVCalculatorOutputNumber,MedicalDrugDeductiblesIntegrated,MedicalDrugMaximumOutofPocketIntegrated,MultipleInNetworkTiers,FirstTierUtilization,SecondTierUtilization,SBCHavingaBabyDeductible,SBCHavingaBabyCopayment,SBCHavingaBabyCoinsurance,SBCHavingaBabyLimit,SBCHavingDiabetesDeductible,SBCHavingDiabetesCopayment,SBCHavingDiabetesCoinsurance,SBCHavingDiabetesLimit,SBCHavingSimplefractureDeductible,SBCHavingSimplefractureCopayment,SBCHavingSimplefractureCoinsurance,SBCHavingSimplefractureLimit,SpecialtyDrugMaximumCoinsurance,InpatientCopaymentMaximumDays,BeginPrimaryCareCostSharingAfterNumberOfVisits,BeginPrimaryCareDeductibleCoinsuranceAfterNumberOfCopays,MEHBInnTier1IndividualMOOP,MEHBInnTier1FamilyPerPersonMOOP,MEHBInnTier1FamilyPerGroupMOOP,MEHBInnTier2IndividualMOOP,MEHBInnTier2FamilyPerPersonMOOP,MEHBInnTier2FamilyPerGroupMOOP,MEHBOutOfNetIndividualMOOP,MEHBOutOfNetFamilyPerPersonMOOP,MEHBOutOfNetFamilyPerGroupMOOP,MEHBCombInnOonIndividualMOOP,MEHBCombInnOonFamilyPerPersonMOOP,MEHBCombInnOonFamilyPerGroupMOOP,DEHBInnTier1IndividualMOOP,DEHBInnTier1FamilyPerPersonMOOP,DEHBInnTier1FamilyPerGroupMOOP,DEHBInnTier2IndividualMOOP,DEHBInnTier2FamilyPerPersonMOOP,DEHBInnTier2FamilyPerGroupMOOP,DEHBOutOfNetIndividualMOOP,DEHBOutOfNetFamilyPerPersonMOOP,DEHBOutOfNetFamilyPerGroupMOOP,DEHBCombInnOonIndividualMOOP,DEHBCombInnOonFamilyPerPersonMOOP,DEHBCombInnOonFamilyPerGroupMOOP,TEHBInnTier1IndividualMOOP,TEHBInnTier1FamilyPerPersonMOOP,TEHBInnTier1FamilyPerGroupMOOP,TEHBInnTier2IndividualMOOP,TEHBInnTier2FamilyPerPersonMOOP,TEHBInnTier2FamilyPerGroupMOOP,TEHBOutOfNetIndividualMOOP,TEHBOutOfNetFamilyPerPersonMOOP,TEHBOutOfNetFamilyPerGroupMOOP,TEHBCombInnOonIndividualMOOP,TEHBCombInnOonFamilyPerPersonMOOP,TEHBCombInnOonFamilyPerGroupMOOP,MEHBDedInnTier1Individual,MEHBDedInnTier1FamilyPerPerson,MEHBDedInnTier1FamilyPerGroup,MEHBDedInnTier1Coinsurance,MEHBDedInnTier2Individual,MEHBDedInnTier2FamilyPerPerson,MEHBDedInnTier2FamilyPerGroup,MEHBDedInnTier2Coinsurance,MEHBDedOutOfNetIndividual,MEHBDedOutOfNetFamilyPerPerson,MEHBDedOutOfNetFamilyPerGroup,MEHBDedCombInnOonIndividual,MEHBDedCombInnOonFamilyPerPerson,MEHBDedCombInnOonFamilyPerGroup,DEHBDedInnTier1Individual,DEHBDedInnTier1FamilyPerPerson,DEHBDedInnTier1FamilyPerGroup,DEHBDedInnTier1Coinsurance,DEHBDedInnTier2Individual,DEHBDedInnTier2FamilyPerPerson,DEHBDedInnTier2FamilyPerGroup,DEHBDedInnTier2Coinsurance,DEHBDedOutOfNetIndividual,DEHBDedOutOfNetFamilyPerPerson,DEHBDedOutOfNetFamilyPerGroup,DEHBDedCombInnOonIndividual,DEHBDedCombInnOonFamilyPerPerson,DEHBDedCombInnOonFamilyPerGroup,TEHBDedInnTier1Individual,TEHBDedInnTier1FamilyPerPerson,TEHBDedInnTier1FamilyPerGroup,TEHBDedInnTier1Coinsurance,TEHBDedInnTier2Individual,TEHBDedInnTier2FamilyPerPerson,TEHBDedInnTier2FamilyPerGroup,TEHBDedInnTier2Coinsurance,TEHBDedOutOfNetIndividual,TEHBDedOutOfNetFamilyPerPerson,TEHBDedOutOfNetFamilyPerGroup,TEHBDedCombInnOonIndividual,TEHBDedCombInnOonFamilyPerPerson,TEHBDedCombInnOonFamilyPerGroup,IsHSAEligible,HSAOrHRAEmployerContribution,HSAOrHRAEmployerContributionAmount,URLForSummaryofBenefitsCoverage,PlanBrochure
0,2026,AK,21989,Delta Dental of Alaska,HIOS,10/15/2025,Individual,Yes,21989AK0030001,Delta Dental Premier Plan,21989AK003,AKN003,AKS003,NaN,Existing,Indemnity,Low,NaN,NaN,Both,NaN,NaN,NaN,NaN,NaN,No,Allows Adult and Child-Only,NaN,NaN,NaN,NaN,1.0,Guaranteed Rate,1/1/2026,12/31/2026,Yes,Non-participating provider benefits,Yes,Non-participating provider benefits,Yes,https://www.deltadentalak.com/member/online-tools/member-dashboard,NaN,21989AK0030001-00,Delta Dental Premier Plan,Standard Low Off Exchange Plan,NaN,NaN,NaN,NaN,No,100%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,Not Applicable,per person not applicable,per group not applicable,NaN,NaN,NaN,Not Applicable,per person not applicable,per group not applicable,$450,$450 per person,$900 per group,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not Applicable,per person not applicable,per group not applicable,NaN,NaN,NaN,NaN,NaN,Not Applicable,per person not applicable,per group not applicable,$0,$0 per person,$0 per group,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.deltadentalak.com/-/media/deltadental/downloads/alaska/shared/brochures/2026/Moda-IND-DEN-Brochure-2026-...
1,2026,AK,21989,Delta Dental of Alaska,HIOS,10/15/2025,Individual,Yes,21989AK0030001,Delta Dental Premier Plan,21989AK003,AKN003,AKS003,NaN,Existing,Indemnity,Low,NaN,NaN,Both,NaN,NaN,NaN,NaN,NaN,No,Allows Adult and Child-Only,NaN,NaN,NaN,NaN,1.0,Guaranteed Rate,1/1/2026,12/31/2026,Yes,Non-participating provider benefits,Yes,Non-participating provider benefits,Yes,https://www.deltadentalak.com/member/online-tools/member-dashboard,NaN,21989AK0030001-01,Delta Dental Premier Plan,Standard Low On Exchange Plan,NaN,NaN,NaN,NaN,No,100%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,Not Applicable,per person not applicable,per group not applicable,NaN,NaN,NaN,Not Applicable,per person not applicable,per group not applicable,$450,$450 per person,$900 per group,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not Applicable,per person not applicable,per group not applicable,NaN,NaN,NaN,NaN,NaN,Not Applicable,per person not applicable,per group not applicable,$0,$0 per person,$0 per group,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.deltadentalak.com/-/media/deltadental/downloads/alaska/shared/brochures/2026/Moda-IND-DEN-Brochure-2026-...
2,2026,AK,21989,Delta Dental of Alaska,HIOS,10/15/2025,Individual,Yes,21989AK0050001,Delta Dental PPO 1000 Plan,21989AK005,AKN004,AKS004,NaN,Existing,PPO,High,NaN,NaN,Both,NaN,NaN,NaN,NaN,NaN,No,Allows Adult and Child-Only,NaN,NaN,NaN,NaN,1.0,Guaranteed Rate,1/1/2026,12/31/2026,Yes,Out-of-network benefits,Yes,Out-of-network benefits,Yes,https://www.deltadentalak.com/member/online-tools/member-dashboard,NaN,21989AK0050001-00,Delta Dental PPO 1000 Plan,Standard High Off Exchange Plan,NaN,NaN,NaN,NaN,No,100%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,$450,$450 per person,$900 per group,NaN,NaN,NaN,Not Applicable,per person not applicable,per group not applicable,Not Applicable,per person not applicable,per group not applicable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not Applicable,per person not applicable,per group not applicable,NaN,NaN,NaN,NaN,NaN,Not Applicable,per person not applicable,per group not applicable,$50,$50 per person,$150 per group,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.deltadentalak.com/-/media/deltadental/downloads/alaska/shared/brochures/2026/Moda-IND-DEN-Brochure-2026-...
3,2026,AK,21989,Delta Dental of Alaska,HIOS,10/15/2025,Individual,Yes,21989AK0050001,Delta Dental PPO 1000 Plan,21989AK005,AKN004,AKS004,NaN,Existing,PPO,High,NaN,NaN,Both,NaN,NaN,NaN,NaN,NaN,No,Allows Adult and Child-Only,NaN,NaN,NaN,NaN,1.0,Guaranteed Rate,1/1/2026,12/31/2026,Yes,Out-of-network benefits,Yes,Out-of-network benefits,Yes,https://www.deltadentalak.com/member/online-tools/member-dashboard,NaN,21989AK0050001-01,Delta Dental PPO 1000 Plan,Standard High On Exchange Plan,NaN,NaN,NaN,NaN,No,100%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,$450,$450 per person,$900 per group,NaN,NaN,NaN,Not Applicable,per person not applicable,per group not applicable,Not Applicable,per person not applicable,per group not applicable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not Applicable,per person not applicable,per group not applicable,NaN,NaN,NaN,NaN,NaN,Not Applicable,per person not applicable,per group not applicable,$50,$50 per person,$150 per group,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.deltadentalak.com/-/media/deltadental/downloads/alaska/shared/brochures/2026/Moda-IND-DEN-Brochure-2026-...
4,2026,AK,21989,Delta Dental of Alaska,HIOS,10/15/2025,Individual,Yes,21989AK0050002,Delta Dental PPO 1500 Plan,21989AK005,AKN004,AKS004,NaN,Existing,PPO,High,NaN,NaN,Both,NaN,NaN,NaN,NaN,NaN,No,Allows Adult and Child-Only,NaN,NaN,NaN,NaN,1.0,Guaranteed Rate,1/1/2026,12/31/2026,Yes,Out-of-network benefits,Yes,Out-of-network benefits,Yes,https://www.deltadentalak.com/member/online-tools/member-dashboard,NaN,21989AK0050002-00,Delta Dental PPO 1500 Plan,Standard High Off Exchange Plan,NaN,NaN,NaN,NaN,No,100%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,$450,$450 per person,$900 per group,NaN,NaN,NaN,Not Applicable,per person not applicable,per group not applicable,Not Applicable,per person not applicable,per group not applicable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not Applicable,per person not applicable,per group not applicable,NaN,NaN,NaN,NaN,NaN,Not Applicable,per person not applicable,per group not applicable,$50,$50 per person,$150 per group,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.deltadentalak.com/-/media/deltadental/downloads/alaska/shared/brochures/2026/Moda-IND-DEN-Brochure-2026-...

In [97]:
# Inspect plan columns, data types, and missing values

plan_columns = pd.DataFrame({
    "column": plan_df.columns,
    "dtype": [plan_df[col].dtype for col in plan_df.columns],
    "missing_count": [plan_df[col].isna().sum() for col in plan_df.columns],
    "missing_pct": [(plan_df[col].isna().mean() * 100).round(2) for col in plan_df.columns],
})

display(plan_columns.sort_values("missing_pct", ascending=False))

                             column    dtype  missing_count  missing_pct
80       DEHBInnTier1IndividualMOOP  float64          22059        100.0
82   DEHBInnTier1FamilyPerGroupMOOP  float64          22059        100.0
81  DEHBInnTier1FamilyPerPersonMOOP  float64          22059        100.0
86       DEHBOutOfNetIndividualMOOP  float64          22059        100.0
84  DEHBInnTier2FamilyPerPersonMOOP  float64          22059        100.0
..                              ...      ...            ...          ...
49           MultipleInNetworkTiers   object              0          0.0
50             FirstTierUtilization   object              0          0.0
44                 CSRVariationType   object              0          0.0
33                PlanEffectiveDate   object              0          0.0
25           CompositeRatingOffered   object              0          0.0

[151 rows x 4 columns]

In [98]:
# Search for important columns by keyword

def search_columns(df, keywords):
    matches = []

    for col in df.columns:
        col_lower = col.lower()

        if any(keyword.lower() in col_lower for keyword in keywords):
            matches.append(col)

    return matches


search_terms = {
    "plan_id": ["planid", "standardcomponentid"],
    "plan_name": ["planmarketingname", "marketing"],
    "issuer": ["issuer"],
    "state": ["state"],
    "metal": ["metal"],
    "plan_type": ["plantype", "type"],
    "deductible": ["deductible", "deduct"],
    "out_of_pocket": ["outofpocket", "out of pocket", "moop", "maximum"],
    "hsa": ["hsa"],
    "network": ["network"],
}

for label, keywords in search_terms.items():
    print(f"\n{label.upper()}")
    print(search_columns(plan_df, keywords))

PLAN_ID
['StandardComponentId', 'ChildOnlyPlanId', 'PlanId']

PLAN_NAME
['IssuerMarketPlaceMarketingName', 'PlanMarketingName', 'PlanVariantMarketingName']

ISSUER
['IssuerId', 'IssuerMarketPlaceMarketingName', 'IssuerActuarialValue']

STATE
['StateCode']

METAL
['MetalLevel']

PLAN_TYPE
['PlanType', 'DesignType', 'QHPNonQHPTypeId', 'CSRVariationType']

DEDUCTIBLE
['MedicalDrugDeductiblesIntegrated', 'SBCHavingaBabyDeductible', 'SBCHavingDiabetesDeductible', 'SBCHavingSimplefractureDeductible', 'BeginPrimaryCareDeductibleCoinsuranceAfterNumberOfCopays']

OUT_OF_POCKET
['MedicalDrugMaximumOutofPocketIntegrated', 'SpecialtyDrugMaximumCoinsurance', 'InpatientCopaymentMaximumDays', 'MEHBInnTier1IndividualMOOP', 'MEHBInnTier1FamilyPerPersonMOOP', 'MEHBInnTier1FamilyPerGroupMOOP', 'MEHBInnTier2IndividualMOOP', 'MEHBInnTier2FamilyPerPersonMOOP', 'MEHBInnTier2FamilyPerGroupMOOP', 'MEHBOutOfNetIndividualMOOP', 'MEHBOutOfNetFamilyPerPersonMOOP', 'MEHBOutOfNetFamilyPerGroupMOOP', 'MEHBCombInnOonIndividualMOOP', 'MEHBCombInnOonFamilyPerPersonMOOP', 'MEHBCombInnOonFamilyPerGroupMOOP', 'DEHBInnTier1IndividualMOOP', 'DEHBInnTier1FamilyPerPersonMOOP', 'DEHBInnTier1FamilyPerGroupMOOP', 'DEHBInnTier2IndividualMOOP', 'DEHBInnTier2FamilyPerPersonMOOP', 'DEHBInnTier2FamilyPerGroupMOOP', 'DEHBOutOfNetIndividualMOOP', 'DEHBOutOfNetFamilyPerPersonMOOP', 'DEHBOutOfNetFamilyPerGroupMOOP', 'DEHBCombInnOonIndividualMOOP', 'DEHBCombInnOonFamilyPerPersonMOOP', 'DEHBCombInnOonFamilyPerGroupMOOP', 'TEHBInnTier1IndividualMOOP', 'TEHBInnTier1FamilyPerPersonMOOP', 'TEHBInnTier1FamilyPerGroupMOOP', 'TEHBInnTier2IndividualMOOP', 'TEHBInnTier2FamilyPerPersonMOOP', 'TEHBInnTier2FamilyPerGroupMOOP', 'TEHBOutOfNetIndividualMOOP', 'TEHBOutOfNetFamilyPerPersonMOOP', 'TEHBOutOfNetFamilyPerGroupMOOP', 'TEHBCombInnOonIndividualMOOP', 'TEHBCombInnOonFamilyPerPersonMOOP', 'TEHBCombInnOonFamilyPerGroupMOOP']

HSA
['IsHSAEligible', 'HSAOrHRAEmployerContribution', 'HSAOrHRAEmployerContributionAmount']

NETWORK
['NetworkId', 'NationalNetwork', 'MultipleInNetworkTiers']

In [99]:
# Map CMS columns to clean project column names
# Note: CMS 2026 Plan Attributes uses IssuerMarketPlaceMarketingName instead of IssuerName.

def get_first_existing_column(df, candidates):
    for col in candidates:
        if col in df.columns:
            return col

    return None


column_map = {
    "plan_id": get_first_existing_column(
        plan_df,
        [
            "StandardComponentId",
            "PlanId",
        ],
    ),
    "issuer_id": get_first_existing_column(
        plan_df,
        [
            "IssuerId",
        ],
    ),
    "issuer_name": get_first_existing_column(
        plan_df,
        [
            "IssuerMarketPlaceMarketingName",
            "IssuerName",
        ],
    ),
    "state": get_first_existing_column(
        plan_df,
        [
            "StateCode",
            "State",
        ],
    ),
    "plan_name": get_first_existing_column(
        plan_df,
        [
            "PlanMarketingName",
            "PlanVariantMarketingName",
        ],
    ),
    "metal_level": get_first_existing_column(
        plan_df,
        [
            "MetalLevel",
        ],
    ),
    "plan_type": get_first_existing_column(
        plan_df,
        [
            "PlanType",
        ],
    ),
    "hsa_eligible": get_first_existing_column(
        plan_df,
        [
            "IsHSAEligible",
        ],
    ),
    "deductible_integrated": get_first_existing_column(
        plan_df,
        [
            "MedicalDrugDeductiblesIntegrated",
        ],
    ),
    "oop_integrated": get_first_existing_column(
        plan_df,
        [
            "MedicalDrugMaximumOutofPocketIntegrated",
        ],
    ),
    "individual_moop": get_first_existing_column(
        plan_df,
        [
            "MEHBInnTier1IndividualMOOP",
            "TEHBInnTier1IndividualMOOP",
        ],
    ),
}

column_map

{'plan_id': 'StandardComponentId',
 'issuer_id': 'IssuerId',
 'issuer_name': 'IssuerMarketPlaceMarketingName',
 'state': 'StateCode',
 'plan_name': 'PlanMarketingName',
 'metal_level': 'MetalLevel',
 'plan_type': 'PlanType',
 'hsa_eligible': 'IsHSAEligible',
 'deductible_integrated': 'MedicalDrugDeductiblesIntegrated',
 'oop_integrated': 'MedicalDrugMaximumOutofPocketIntegrated',
 'individual_moop': 'MEHBInnTier1IndividualMOOP'}

In [100]:
# Build clean plan dataframe from selected columns

clean_plan_df = pd.DataFrame()

for clean_col, source_col in column_map.items():
    if source_col is None:
        clean_plan_df[clean_col] = np.nan
    else:
        clean_plan_df[clean_col] = plan_df[source_col]

print("Clean plan shape:", clean_plan_df.shape)
display(clean_plan_df.head())

Clean plan shape: (22059, 11)

,plan_id,issuer_id,issuer_name,state,plan_name,metal_level,plan_type,hsa_eligible,deductible_integrated,oop_integrated,individual_moop
0,21989AK0030001,21989,Delta Dental of Alaska,AK,Delta Dental Premier Plan,Low,Indemnity,NaN,NaN,NaN,Not Applicable
1,21989AK0030001,21989,Delta Dental of Alaska,AK,Delta Dental Premier Plan,Low,Indemnity,NaN,NaN,NaN,Not Applicable
2,21989AK0050001,21989,Delta Dental of Alaska,AK,Delta Dental PPO 1000 Plan,High,PPO,NaN,NaN,NaN,$450
3,21989AK0050001,21989,Delta Dental of Alaska,AK,Delta Dental PPO 1000 Plan,High,PPO,NaN,NaN,NaN,$450
4,21989AK0050002,21989,Delta Dental of Alaska,AK,Delta Dental PPO 1500 Plan,High,PPO,NaN,NaN,NaN,$450

In [101]:
# Clean text columns

text_cols = [
    "plan_id",
    "issuer_id",
    "issuer_name",
    "state",
    "plan_name",
    "metal_level",
    "plan_type",
    "hsa_eligible",
    "deductible_integrated",
    "oop_integrated",
]

for col in text_cols:
    clean_plan_df[col] = (
        clean_plan_df[col]
        .astype("string")
        .str.strip()
        .replace({
            "": pd.NA,
            "nan": pd.NA,
            "None": pd.NA,
            "Not Applicable": pd.NA,
        })
    )

display(clean_plan_df.head())

,plan_id,issuer_id,issuer_name,state,plan_name,metal_level,plan_type,hsa_eligible,deductible_integrated,oop_integrated,individual_moop
0,21989AK0030001,21989,Delta Dental of Alaska,AK,Delta Dental Premier Plan,Low,Indemnity,<NA>,<NA>,<NA>,Not Applicable
1,21989AK0030001,21989,Delta Dental of Alaska,AK,Delta Dental Premier Plan,Low,Indemnity,<NA>,<NA>,<NA>,Not Applicable
2,21989AK0050001,21989,Delta Dental of Alaska,AK,Delta Dental PPO 1000 Plan,High,PPO,<NA>,<NA>,<NA>,$450
3,21989AK0050001,21989,Delta Dental of Alaska,AK,Delta Dental PPO 1000 Plan,High,PPO,<NA>,<NA>,<NA>,$450
4,21989AK0050002,21989,Delta Dental of Alaska,AK,Delta Dental PPO 1500 Plan,High,PPO,<NA>,<NA>,<NA>,$450

In [102]:
# Clean numeric out-of-pocket field
# The deductible_integrated and oop_integrated fields are design indicators, not dollar amounts.

def clean_money(value):
    if pd.isna(value):
        return np.nan

    value = str(value).strip()

    if value.lower() in ["", "nan", "none", "not applicable", "not available"]:
        return np.nan

    if "no charge" in value.lower():
        return 0.0

    value = (
        value
        .replace("$", "")
        .replace(",", "")
        .replace("%", "")
        .strip()
    )

    try:
        return float(value)
    except ValueError:
        return np.nan


clean_plan_df["out_of_pocket_individual"] = clean_plan_df["individual_moop"].apply(clean_money)

display(
    clean_plan_df[
        [
            "deductible_integrated",
            "oop_integrated",
            "individual_moop",
            "out_of_pocket_individual",
        ]
    ].head()
)

display(clean_plan_df[["out_of_pocket_individual"]].describe())

  deductible_integrated oop_integrated individual_moop  out_of_pocket_individual
0                  <NA>           <NA>  Not Applicable                       NaN
1                  <NA>           <NA>  Not Applicable                       NaN
2                  <NA>           <NA>           $450                      450.0
3                  <NA>           <NA>           $450                      450.0
4                  <NA>           <NA>           $450                      450.0

       out_of_pocket_individual
count               1121.000000
mean                 426.003568
std                   77.442352
min                    0.000000
25%                  450.000000
50%                  450.000000
75%                  450.000000
max                  450.000000

In [103]:
# Check missing values after cleaning

missing_summary = clean_plan_df.isna().sum().reset_index()
missing_summary.columns = ["column", "missing_count"]
missing_summary["missing_pct"] = (missing_summary["missing_count"] / len(clean_plan_df) * 100).round(2)

display(missing_summary.sort_values("missing_pct", ascending=False))

                      column  missing_count  missing_pct
11  out_of_pocket_individual          20938        94.92
10           individual_moop          20670        93.70
9             oop_integrated           1389         6.30
7               hsa_eligible           1389         6.30
8      deductible_integrated           1389         6.30
2                issuer_name              0         0.00
1                  issuer_id              0         0.00
0                    plan_id              0         0.00
3                      state              0         0.00
6                  plan_type              0         0.00
4                  plan_name              0         0.00
5                metal_level              0         0.00

In [104]:
# Remove rows missing core plan identity fields only
# Do not remove rows because benefit design fields are missing.

before_rows = len(clean_plan_df)

required_cols = [
    "plan_id",
    "plan_name",
    "issuer_name",
    "state",
]

clean_plan_df = clean_plan_df.dropna(subset=required_cols).copy()

after_rows = len(clean_plan_df)

print("Rows before:", before_rows)
print("Rows after:", after_rows)
print("Rows removed:", before_rows - after_rows)

display(clean_plan_df.head())

Rows before: 22059
Rows after: 22059
Rows removed: 0

,plan_id,issuer_id,issuer_name,state,plan_name,metal_level,plan_type,hsa_eligible,deductible_integrated,oop_integrated,individual_moop,out_of_pocket_individual
0,21989AK0030001,21989,Delta Dental of Alaska,AK,Delta Dental Premier Plan,Low,Indemnity,<NA>,<NA>,<NA>,Not Applicable,NaN
1,21989AK0030001,21989,Delta Dental of Alaska,AK,Delta Dental Premier Plan,Low,Indemnity,<NA>,<NA>,<NA>,Not Applicable,NaN
2,21989AK0050001,21989,Delta Dental of Alaska,AK,Delta Dental PPO 1000 Plan,High,PPO,<NA>,<NA>,<NA>,$450,450.0
3,21989AK0050001,21989,Delta Dental of Alaska,AK,Delta Dental PPO 1000 Plan,High,PPO,<NA>,<NA>,<NA>,$450,450.0
4,21989AK0050002,21989,Delta Dental of Alaska,AK,Delta Dental PPO 1500 Plan,High,PPO,<NA>,<NA>,<NA>,$450,450.0

In [105]:
# Remove duplicate plan records

duplicate_count = clean_plan_df.duplicated(subset=["plan_id"]).sum()

print("Duplicate plan_id count:", duplicate_count)

clean_plan_df = clean_plan_df.drop_duplicates(subset=["plan_id"]).reset_index(drop=True)

print("Final shape:", clean_plan_df.shape)

Duplicate plan_id count: 16915
Final shape: (5144, 12)

In [106]:
# Basic plan data summary

print("Number of plans:", clean_plan_df["plan_id"].nunique())
print("Number of issuers:", clean_plan_df["issuer_name"].nunique())
print("Number of states:", clean_plan_df["state"].nunique())

display(clean_plan_df["metal_level"].value_counts(dropna=False).to_frame("count"))
display(clean_plan_df["plan_type"].value_counts(dropna=False).to_frame("count"))
display(clean_plan_df["state"].value_counts(dropna=False).to_frame("count").head(20))

Number of plans: 5144
Number of issuers: 161
Number of states: 30

                 count
metal_level
Silver            1528
Gold              1217
Expanded Bronze   1180
Low                523
High               419
Bronze             149
Catastrophic        75
Platinum            53

           count
plan_type
HMO         2239
PPO         1305
EPO         1126
POS          438
Indemnity     36

       count
state
TX       896
FL       464
WI       400
OH       283
NC       239
MI       230
AZ       226
OK       216
TN       187
NE       180
MO       160
SC       152
NH       140
MT       139
IA       135
IN       135
LA       128
AL        94
UT        86
KS        83

In [107]:
# Numeric summary for out-of-pocket values

display(
    clean_plan_df[
        [
            "out_of_pocket_individual",
        ]
    ].describe()
)

       out_of_pocket_individual
count                761.000000
mean                 421.944809
std                   90.981647
min                    0.000000
25%                  450.000000
50%                  450.000000
75%                  450.000000
max                  450.000000

In [108]:
# Preview plans with available out-of-pocket data

plans_with_oop = (
    clean_plan_df
    .dropna(subset=["out_of_pocket_individual"])
    .sort_values("out_of_pocket_individual")
    [
        [
            "plan_name",
            "issuer_name",
            "state",
            "metal_level",
            "plan_type",
            "deductible_integrated",
            "oop_integrated",
            "out_of_pocket_individual",
        ]
    ]
    .head(20)
)

display(plans_with_oop)

                                          plan_name issuer_name state metal_level plan_type deductible_integrated oop_integrated  out_of_pocket_individual
2935  Dental Plan 8 with Ortho Rider - Non-Alliance   MedMutual    OH        High       PPO                  <NA>           <NA>                       0.0
2936       Dental Plan 8 (Voluntary) - Non-Alliance   MedMutual    OH        High       PPO                  <NA>           <NA>                       0.0
2913           Dental Plan 5 (Voluntary) - Alliance   MedMutual    OH        High       PPO                  <NA>           <NA>                       0.0
2971                             MedMutual Dental 1   MedMutual    OH        High       PPO                  <NA>           <NA>                       0.0
2930       Dental Plan 6 (Voluntary) - Non-Alliance   MedMutual    OH        High       PPO                  <NA>           <NA>                       0.0
2929  Dental Plan 6 with Ortho Rider - Non-Alliance   MedMutual    OH        High       PPO                  <NA>           <NA>                       0.0
2972                             MedMutual Dental 2   MedMutual    OH        High       PPO                  <NA>           <NA>                       0.0
2931                   Dental Plan 7 - Non-Alliance   MedMutual    OH        High       PPO                  <NA>           <NA>                       0.0
2934                   Dental Plan 8 - Non-Alliance   MedMutual    OH        High       PPO                  <NA>           <NA>                       0.0
2933       Dental Plan 7 (Voluntary) - Non-Alliance   MedMutual    OH        High       PPO                  <NA>           <NA>                       0.0
2932  Dental Plan 7 with Ortho Rider - Non-Alliance   MedMutual    OH        High       PPO                  <NA>           <NA>                       0.0
2914                       Dental Plan 6 - Alliance   MedMutual    OH        High       PPO                  <NA>           <NA>                       0.0
2973                             MedMutual Dental 3   MedMutual    OH        High       PPO                  <NA>           <NA>                       0.0
2917                       Dental Plan 7 - Alliance   MedMutual    OH        High       PPO                  <NA>           <NA>                       0.0
2912                       Dental Plan 5 - Alliance   MedMutual    OH        High       PPO                  <NA>           <NA>                       0.0
2911           Dental Plan 4 (Voluntary) - Alliance   MedMutual    OH        High       PPO                  <NA>           <NA>                       0.0
2910      Dental Plan 4 with Ortho Rider - Alliance   MedMutual    OH        High       PPO                  <NA>           <NA>                       0.0
2909                       Dental Plan 4 - Alliance   MedMutual    OH        High       PPO                  <NA>           <NA>                       0.0
2928                   Dental Plan 6 - Non-Alliance   MedMutual    OH        High       PPO                  <NA>           <NA>                       0.0
2927       Dental Plan 5 (Voluntary) - Non-Alliance   MedMutual    OH        High       PPO                  <NA>           <NA>                       0.0

In [109]:
# Create readable values for RAG text

rag_df = clean_plan_df.copy()

rag_df["hsa_eligible_text"] = rag_df["hsa_eligible"].fillna("Not available")
rag_df["deductible_integrated_text"] = rag_df["deductible_integrated"].fillna("Not available")
rag_df["oop_integrated_text"] = rag_df["oop_integrated"].fillna("Not available")

rag_df["out_of_pocket_individual_text"] = rag_df["out_of_pocket_individual"].apply(
    lambda x: "Not available" if pd.isna(x) else f"${x:,.0f}"
)

display(
    rag_df[
        [
            "plan_name",
            "hsa_eligible_text",
            "deductible_integrated_text",
            "oop_integrated_text",
            "out_of_pocket_individual_text",
        ]
    ].head()
)

                                  plan_name hsa_eligible_text deductible_integrated_text oop_integrated_text out_of_pocket_individual_text
0                 Delta Dental Premier Plan     Not available              Not available       Not available                 Not available
1                Delta Dental PPO 1000 Plan     Not available              Not available       Not available                          $450
2                Delta Dental PPO 1500 Plan     Not available              Not available       Not available                          $450
3       Delta Dental Premier Healthy Smiles     Not available              Not available       Not available                 Not available
4  Delta Dental Premier 1000, 100/80/50, 50     Not available              Not available       Not available                 Not available

In [110]:
# Build RAG text for each plan

def build_plan_summary(row):
    return f"""
Plan Name: {row["plan_name"]}
Plan ID: {row["plan_id"]}
Issuer: {row["issuer_name"]}
State: {row["state"]}
Metal Level: {row["metal_level"]}
Plan Type: {row["plan_type"]}
HSA Eligible: {row["hsa_eligible_text"]}

Deductible Design:
Medical and drug deductibles integrated: {row["deductible_integrated_text"]}.

Out-of-Pocket Design:
Medical and drug maximum out-of-pocket integrated: {row["oop_integrated_text"]}.
The individual in-network tier 1 maximum out-of-pocket amount is {row["out_of_pocket_individual_text"]}.

Benefits Context:
This plan record comes from public CMS Exchange Public Use File data.
It can be used for benefits search, plan comparison, document retrieval, and RAG question answering.
""".strip()


clean_plan_df["rag_text"] = rag_df.apply(build_plan_summary, axis=1)

display(clean_plan_df[["plan_id", "plan_name", "rag_text"]].head())

,plan_id,plan_name,rag_text
0,21989AK0030001,Delta Dental Premier Plan,Plan Name: Delta Dental Premier Plan\nPlan ID: 21989AK0030001\nIssuer: Delta Dental of Alaska\nState: AK\nMetal Leve...
1,21989AK0050001,Delta Dental PPO 1000 Plan,Plan Name: Delta Dental PPO 1000 Plan\nPlan ID: 21989AK0050001\nIssuer: Delta Dental of Alaska\nState: AK\nMetal Lev...
2,21989AK0050002,Delta Dental PPO 1500 Plan,Plan Name: Delta Dental PPO 1500 Plan\nPlan ID: 21989AK0050002\nIssuer: Delta Dental of Alaska\nState: AK\nMetal Lev...
3,21989AK0070001,Delta Dental Premier Healthy Smiles,Plan Name: Delta Dental Premier Healthy Smiles\nPlan ID: 21989AK0070001\nIssuer: Delta Dental of Alaska\nState: AK\n...
4,21989AK0080001,"Delta Dental Premier 1000, 100/80/50, 50","Plan Name: Delta Dental Premier 1000, 100/80/50, 50\nPlan ID: 21989AK0080001\nIssuer: Delta Dental of Alaska\nState:..."

In [111]:
# Save clean plan dataset

clean_output_path = PREPROCESSED_DIR / "clean_plan_data.csv"

clean_plan_df.to_csv(clean_output_path, index=False)

print("Saved:", clean_output_path)
print("Shape:", clean_plan_df.shape)

Saved: c:\Users\tevin\OneDrive\Desktop\LLM-And-Generative-AI\rag\benefits_ai_platform\data\02_preprocessed\clean_plan_data.csv
Shape: (5144, 13)

In [112]:
# Create RAG-ready full and sample datasets

rag_ready_df = clean_plan_df[
    [
        "plan_id",
        "issuer_id",
        "issuer_name",
        "state",
        "plan_name",
        "metal_level",
        "plan_type",
        "hsa_eligible",
        "deductible_integrated",
        "oop_integrated",
        "out_of_pocket_individual",
        "rag_text",
    ]
].copy()

rag_ready_sample_df = rag_ready_df.head(1000).copy()

print("RAG-ready full shape:", rag_ready_df.shape)
print("RAG-ready sample shape:", rag_ready_sample_df.shape)

display(rag_ready_sample_df.head())

RAG-ready full shape: (5144, 12)
RAG-ready sample shape: (1000, 12)

,plan_id,issuer_id,issuer_name,state,plan_name,metal_level,plan_type,hsa_eligible,deductible_integrated,oop_integrated,out_of_pocket_individual,rag_text
0,21989AK0030001,21989,Delta Dental of Alaska,AK,Delta Dental Premier Plan,Low,Indemnity,<NA>,<NA>,<NA>,NaN,Plan Name: Delta Dental Premier Plan\nPlan ID: 21989AK0030001\nIssuer: Delta Dental of Alaska\nState: AK\nMetal Leve...
1,21989AK0050001,21989,Delta Dental of Alaska,AK,Delta Dental PPO 1000 Plan,High,PPO,<NA>,<NA>,<NA>,450.0,Plan Name: Delta Dental PPO 1000 Plan\nPlan ID: 21989AK0050001\nIssuer: Delta Dental of Alaska\nState: AK\nMetal Lev...
2,21989AK0050002,21989,Delta Dental of Alaska,AK,Delta Dental PPO 1500 Plan,High,PPO,<NA>,<NA>,<NA>,450.0,Plan Name: Delta Dental PPO 1500 Plan\nPlan ID: 21989AK0050002\nIssuer: Delta Dental of Alaska\nState: AK\nMetal Lev...
3,21989AK0070001,21989,Delta Dental of Alaska,AK,Delta Dental Premier Healthy Smiles,Low,Indemnity,<NA>,<NA>,<NA>,NaN,Plan Name: Delta Dental Premier Healthy Smiles\nPlan ID: 21989AK0070001\nIssuer: Delta Dental of Alaska\nState: AK\n...
4,21989AK0080001,21989,Delta Dental of Alaska,AK,"Delta Dental Premier 1000, 100/80/50, 50",High,Indemnity,<NA>,<NA>,<NA>,NaN,"Plan Name: Delta Dental Premier 1000, 100/80/50, 50\nPlan ID: 21989AK0080001\nIssuer: Delta Dental of Alaska\nState:..."

In [113]:
# Save RAG-ready datasets

rag_full_output_path = PREPROCESSED_DIR / "rag_ready_plan_data_full.csv"
rag_sample_output_path = PREPROCESSED_DIR / "rag_ready_plan_data_sample.csv"

rag_ready_df.to_csv(rag_full_output_path, index=False)
rag_ready_sample_df.to_csv(rag_sample_output_path, index=False)

print("Saved:", rag_full_output_path)
print("Saved:", rag_sample_output_path)

Saved: c:\Users\tevin\OneDrive\Desktop\LLM-And-Generative-AI\rag\benefits_ai_platform\data\02_preprocessed\rag_ready_plan_data_full.csv
Saved: c:\Users\tevin\OneDrive\Desktop\LLM-And-Generative-AI\rag\benefits_ai_platform\data\02_preprocessed\rag_ready_plan_data_sample.csv

In [114]:
# Reload saved files to confirm they work

check_clean_df = pd.read_csv(clean_output_path)
check_rag_sample_df = pd.read_csv(rag_sample_output_path)

print("Clean data shape:", check_clean_df.shape)
print("RAG sample shape:", check_rag_sample_df.shape)

display(check_rag_sample_df.head())

Clean data shape: (5144, 13)
RAG sample shape: (1000, 12)

,plan_id,issuer_id,issuer_name,state,plan_name,metal_level,plan_type,hsa_eligible,deductible_integrated,oop_integrated,out_of_pocket_individual,rag_text
0,21989AK0030001,21989,Delta Dental of Alaska,AK,Delta Dental Premier Plan,Low,Indemnity,NaN,NaN,NaN,NaN,Plan Name: Delta Dental Premier Plan\nPlan ID: 21989AK0030001\nIssuer: Delta Dental of Alaska\nState: AK\nMetal Leve...
1,21989AK0050001,21989,Delta Dental of Alaska,AK,Delta Dental PPO 1000 Plan,High,PPO,NaN,NaN,NaN,450.0,Plan Name: Delta Dental PPO 1000 Plan\nPlan ID: 21989AK0050001\nIssuer: Delta Dental of Alaska\nState: AK\nMetal Lev...
2,21989AK0050002,21989,Delta Dental of Alaska,AK,Delta Dental PPO 1500 Plan,High,PPO,NaN,NaN,NaN,450.0,Plan Name: Delta Dental PPO 1500 Plan\nPlan ID: 21989AK0050002\nIssuer: Delta Dental of Alaska\nState: AK\nMetal Lev...
3,21989AK0070001,21989,Delta Dental of Alaska,AK,Delta Dental Premier Healthy Smiles,Low,Indemnity,NaN,NaN,NaN,NaN,Plan Name: Delta Dental Premier Healthy Smiles\nPlan ID: 21989AK0070001\nIssuer: Delta Dental of Alaska\nState: AK\n...
4,21989AK0080001,21989,Delta Dental of Alaska,AK,"Delta Dental Premier 1000, 100/80/50, 50",High,Indemnity,NaN,NaN,NaN,NaN,"Plan Name: Delta Dental Premier 1000, 100/80/50, 50\nPlan ID: 21989AK0080001\nIssuer: Delta Dental of Alaska\nState:..."

In [115]:
# Final notebook summary

print("Notebook 1 complete.")
print("Clean plan records:", len(clean_plan_df))
print("Unique plans:", clean_plan_df["plan_id"].nunique())
print("Unique issuers:", clean_plan_df["issuer_name"].nunique())
print("Unique states:", clean_plan_df["state"].nunique())

print("\nFiles created:")
print("1. data/02_preprocessed/clean_plan_data.csv")
print("2. data/02_preprocessed/rag_ready_plan_data_full.csv")
print("3. data/02_preprocessed/rag_ready_plan_data_sample.csv")

Notebook 1 complete.
Clean plan records: 5144
Unique plans: 5144
Unique issuers: 161
Unique states: 30

Files created:
1. data/02_preprocessed/clean_plan_data.csv
2. data/02_preprocessed/rag_ready_plan_data_full.csv
3. data/02_preprocessed/rag_ready_plan_data_sample.csv